name: firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_storage: 11.2.5
  image_picker: 1.0.1
  path_provider: 2.0.15
  file_picker: 5.3.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

